#!/bin/sh

VER=v2.0.0

test_file_existence() {
    if [ ! -f "$2" ]; then
        echo "ERROR: $1 This operating system does not meet the Properios Core Specification $VER. The file '$2' does not exist."
        exit 1
    fi
}

test_directory_existence() {
    if [ ! -d "$2" ]; then
        echo "ERROR: $1 This operating system does not meet the Properios Core Specification $VER. The directory '$2' does not exist."
        exit 1
    fi
}

test_ownership_group_and_permissions() {
    TEST_CASE=$(stat -c %U $2)
    if [ "$TEST_CASE" != "$3" ]; then
        echo "ERROR: $1 This operating system does not meet the Properios Core Specification $VER. $2's owner is '$TEST_CASE', but it should be '$3'."
        exit 1
    fi

    TEST_CASE=$(stat -c %G $2)
    if [ "$TEST_CASE" != "$4" ]; then
        echo "ERROR: $1 This operating system does not meet the Properios Core Specification $VER. $2's group is '$TEST_CASE', but it should be '$4'."
        exit 1
    fi

    TEST_CASE=$(stat -c %a $2)
    if [ "$TEST_CASE" != "$5" ]; then
        echo "ERROR: $1 This operating system does not meet the Properios Core Specification $VER. $2's file permissions are '$TEST_CASE', but it should be '$5'."
        exit 1
    fi
}

test_ownership_group_and_permissions_on_optional_file() {
    if [ -f "$2" ]; then
        test_ownership_group_and_permissions "$1" "$2" "$3" "$4" "$5"
    else
        echo "INFO: $1 Checked for optional file '$2', but it was not found."
    fi
}

test_ownership_group_and_permissions_on_optional_directory() {
    if [ -d "$2" ]; then
        test_ownership_group_and_permissions "$1" "$2" "$3" "$4" "$5"
    else
        echo "INFO: $1 Checked for optional directory '$2', but it was not found."
    fi
}

test_directory_existence                                    "[Ref. 1.1]"      "/boot"
test_directory_existence                                    "[Ref. 1.1]"      "/dev"
test_directory_existence                                    "[Ref. 1.1]"      "/etc"
test_directory_existence                                    "[Ref. 1.1]"      "/proc"
test_directory_existence                                    "[Ref. 1.1]"      "/root"
test_directory_existence                                    "[Ref. 1.1]"      "/run"
test_directory_existence                                    "[Ref. 1.1]"      "/tmp"
test_directory_existence                                    "[Ref. 1.1]"      "/usr"
test_directory_existence                                    "[Ref. 1.1]"      "/var"
test_ownership_group_and_permissions                        "[Ref. 1.2 (a)]"  "/boot"                                  "root"  "root"  "700"
test_ownership_group_and_permissions                        "[Ref. 1.2 (b)]"  "/dev"                                   "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.2 (c)]"  "/etc"                                   "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (d)]"  "/home"                                  "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (e)]"  "/media"                                 "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (f)]"  "/opt"                                   "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (g)]"  "/mnt"                                   "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.2 (h)]"  "/proc"                                  "root"  "root"  "555"
test_ownership_group_and_permissions                        "[Ref. 1.2 (i)]"  "/root"                                  "root"  "root"  "700"
test_ownership_group_and_permissions                        "[Ref. 1.2 (j)]"  "/run"                                   "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (k)]"  "/srv"                                   "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.2 (l)]"  "/sys"                                   "root"  "root"  "555"
test_ownership_group_and_permissions                        "[Ref. 1.2 (m)]"  "/tmp"                                   "root"  "root"  "1777"
test_ownership_group_and_permissions                        "[Ref. 1.2 (n)]"  "/usr"                                   "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.2 (o)]"  "/var"                                   "root"  "root"  "755"
test_directory_existence                                    "[Ref. 1.3]"      "/usr/bin"
test_directory_existence                                    "[Ref. 1.3]"      "/usr/include"
test_directory_existence                                    "[Ref. 1.3]"      "/usr/lib"
test_directory_existence                                    "[Ref. 1.3]"      "/usr/local"
test_directory_existence                                    "[Ref. 1.3]"      "/usr/sbin"
test_ownership_group_and_permissions                        "[Ref. 1.4 (a)]"  "/usr/bin"                               "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.4 (b)]"  "/usr/include"                           "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.4 (c)]"  "/usr/lib"                               "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.4 (d)]"  "/usr/lib64"                             "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.4 (e)]"  "/usr/local"                             "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.4 (f)]"  "/usr/sbin"                              "root"  "root"  "700"
test_directory_existence                                    "[Ref. 1.5]"      "/usr/local/bin"
test_directory_existence                                    "[Ref. 1.5]"      "/usr/local/include"
test_directory_existence                                    "[Ref. 1.5]"      "/usr/local/lib"
test_directory_existence                                    "[Ref. 1.5]"      "/usr/local/sbin"
test_ownership_group_and_permissions                        "[Ref. 1.6 (a)]"  "/usr/local/bin"                         "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.6 (b)]"  "/usr/local/include"                     "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.6 (c)]"  "/usr/local/lib"                         "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.6 (d)]"  "/usr/local/lib64"                       "root"  "root"  "755"
test_ownership_group_and_permissions                        "[Ref. 1.6 (e)]"  "/usr/local/sbin"                        "root"  "root"  "700"
test_ownership_group_and_permissions                        "[Ref. 1.7]"      "/etc/shells"                            "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.7]"      "/etc/nftables.conf"                     "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.7]"      "/etc/sysctl.conf"                       "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.8]"      "/etc/login.defs"                        "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.8]"      "/etc/nsswitch.conf"                     "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.9]"      "/etc/adduser.conf"                      "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.9]"      "/etc/deluser.conf"                      "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.10]"     "/etc/passwd"                            "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.10]"     "/etc/shadow"                            "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.10]"     "/etc/group"                             "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 1.10]"     "/etc/gshadow"                           "root"  "root"  "600"
test_ownership_group_and_permissions_on_optional_file       "[Ref. 1.11]"     "/etc/crontab"                           "root"  "root"  "600"
test_ownership_group_and_permissions_on_optional_file       "[Ref. 1.11]"     "/etc/xattr.conf"                        "root"  "root"  "600"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/X11"                               "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/apparmor.d"                        "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.d"                            "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.daily"                        "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.hourly"                       "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.monthly"                      "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.weekly"                       "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/cron.yearly"                       "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/dhcp"                              "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/init.d"                            "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/initramfs-tools"                   "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/iproute2"                          "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/kernel"                            "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/modprobe.d"                        "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/modules-load.d"                    "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/network"                           "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/opensc"                            "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc0.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc1.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc2.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc3.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc4.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc5.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rc6.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/rcS.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/selinux"                           "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/skel"                              "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/ssl"                               "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/sysctl.d"                          "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.12]"     "/etc/systemd"                           "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.13]"     "/etc/ssl/private"                       "root"  "root"  "700"
test_ownership_group_and_permissions_on_optional_directory  "[Ref. 1.14]"     "/etc/ssl/certs"                         "root"  "root"  "755"
test_ownership_group_and_permissions_on_optional_file       "[Ref. 1.15]"     "/etc/ssl/openssl.cnf"                   "root"  "root"  "644"
test_ownership_group_and_permissions_on_optional_file       "[Ref. 2.1]"      "/etc/pam.conf"                          "root"  "root"  "600"
test_ownership_group_and_permissions                        "[Ref. 2.2]"      "/etc/pam.d"                             "root"  "root"  "700"
test_ownership_group_and_permissions                        "[Ref. 2.3]"      "/etc/security"                          "root"  "root"  "700"
test_ownership_group_and_permissions                        "[Ref. 2.3]"      "/etc/pam_pkcs11"                        "root"  "root"  "700"
test_file_existence                                         "[Ref. 2.4 (a)]"  "/etc/pam.d/root-auth"

ROOT_AUTH_FILE_EXPECTED_CONTENTS=$(cat <<EOF
#%PAM-1.0
auth    [success=ignore default=1]  pam_succeed_if.so user = root
auth    sufficient  pam_pkcs11.so
EOF
)

if [ "$(cat /etc/pam.d/root-auth)" != "$ROOT_AUTH_FILE_EXPECTED_CONTENTS" ]; then
    echo "ERROR: [Ref. 2.4 (b)] This operating system does not meet the Properios Core Specification $VER. /etc/pam.d/root-auth does not have the expected file contents."
    unset ROOT_AUTH_FILE_EXPECTED_CONTENTS
    exit 1
fi

unset ROOT_AUTH_FILE_EXPECTED_CONTENTS

test_file_existence "[Ref. 2.5 (a)]" "/etc/pam.d/common-auth"

AUTH_STACK_WHITELIST="common-auth root-auth"

for policy_file in /etc/pam.d/*; do
    base=$(basename "$policy_file")

    for whitelisted_file in $AUTH_STACK_WHITELIST; do 
        if [ "$base" = "$whitelisted_file" ]; then
            continue 2  
        fi
    done

    while IFS= read -r line; do
        case "$line" in
            auth[[:space:]]*)
                if echo "$line" | grep -Eq '\bpam_faildelay\.so([[:space:]]|$)'; then
                    continue
                elif echo "$line" | grep -Eq '\bpam_nologin\.so([[:space:]]|$)'; then
                    continue
                elif echo "$line" | grep -Eq '\bpam_rootok\.so\b'; then
                    continue
                elif echo "$line" | grep -Eq '\bpam_shells\.so\b'; then
                    continue
                elif echo "$line" | grep -Eq '^auth[[:space:]]+include[[:space:]]+\S+'; then
                    continue
                else
                    echo "ERROR: [Ref. 2.5 (b)] This operating system does not meet the Properios Core Specification $VER. The PAM policy file '$policy_file' has at least one auth-stack definition, but it is not part of the whitelist in the design specification."
                    unset base
                    unset AUTH_STACK_WHITELIST
                    exit 1
                fi
            ;; 
        esac
    done < "$policy_file"

    unset base
done

unset AUTH_STACK_WHITELIST

FIRST_PAM_COMMON_AUTH_COMMAND=$(grep -v '^[[:space:]]*#' /etc/pam.d/common-auth | grep -v '^[[:space:]]*$' | head -n 1)

if [ ! "$FIRST_PAM_COMMON_AUTH_COMMAND" = "@include root-auth" ]; then
    echo "ERROR: [Ref. 2.5 (c)] This operating system does not meet the Properios Core Specification $VER. Instead of '@include root-auth' (Correct), '$FIRST_PAM_COMMON_AUTH_COMMAND' is the first executable line in '/etc/pam.d/common-auth'."
    unset FIRST_PAM_COMMON_AUTH_COMMAND
    exit 1
fi

unset FIRST_PAM_COMMON_AUTH_COMMAND

PKCS11_PAM_MODULE_LIB=$(find /lib /usr/lib -type f -name 'pam_pkcs11.so' -print -quit)

if [ -z "$PKCS11_PAM_MODULE_LIB" ]; then
    echo "ERROR: [Ref. 2.6] This operating system does not meet the Properios Core Specification $VER. pam_pkcs11.so could not be found."
    unset PKCS11_PAM_MODULE_LIB
    exit 1
fi

unset PKCS11_PAM_MODULE_LIB

USERMOD_COMMANDS="adduser chage chfn chpass chpasswd chsh gpasswd groupadd groupdel groupmod grpck ldappasswd mkpasswd newusers passwd pw pwck pwgen rmuser smbpasswd useradd userdel usermod vigr vipw"

for cmd in $USERMOD_COMMANDS; do 
    CMD_PATH=$(realpath -q "$(command -v "$cmd" 2>/dev/null || echo "")" 2>/dev/null || echo "")
    if [ -n "$CMD_PATH" ]; then 
        test_ownership_group_and_permissions "[Ref. 3.1]" "$CMD_PATH" "root" "root" "700"
    fi 
done

unset USERMOD_COMMANDS

SUDO_BIN=$(realpath -q "$(command -v sudo 2>/dev/null || echo "")" 2>/dev/null || echo "")

if [ -n "$SUDO_BIN" ]; then
    echo "ERROR: [Ref. 4.1] This operating system does not meet the Properios Core Specification $VER. The 'sudo' program was found on the system."
    unset SUDO_BIN
    exit 1
fi

unset SUDO_BIN

./extract-ikconfig "/boot/vmlinuz-$(uname -r)" > /dev/null 2>&1

if [ $? -ne 0 ]; then
    echo "ERROR: [Ref. 5.1] This operating system does not meet the Properios Core Specification $VER. The contents of the kernel .config file were not found within the bootable kernel image located at /boot/vmlinuz-$(uname -r)."
    echo "\n\tTroubleshooting Step #1: Since the extract-ikconfig script does not report whether the reason it can't find the contents of the kernel .config is due to not being able to extract the contents of the file, install all of the following programs and try again: gunzip unxz bunzip2 unlzma lzop lz4 unzstd."
    echo "\n\tTroubleshooting Step #2: Set 'CONFIG_IKCONFIG=y' in the kernel .config file, recompile the kernel, and try again."
    exit 1
fi

echo "SUCCESS: This operating system meets the Properios Core Specification $VER."